// <auto-generated />
namespace ATM_JorisDeRidder_DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class fixbalance : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixbalance));
        
        string IMigrationMetadata.Id
        {
            get { return "202207280735439_fixbalance"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
